spring:
  application:
    name: demo-app
  config:
    activate:
      on-profile: prod  # Use 'on-profile' instead of 'profiles'

server:
  port: 8080
  context-path: /api

logging:
  level:
    root: INFO
    com.cloudcomputing.demo: DEBUG

# CORS Configuration
cors:
  allowed-origins: 
    - http://localhost:3000
  allowed-methods: 
    - GET
    - POST
    - PUT
    - DELETE

---
# Production profile
spring:
  server:
    port: 80  # Change to production port if necessary
  cors:
    allowed-origins: 
      - https://your-production-url.com
    allowed-methods: 
      - GET
      - POST
      - PUT
      - DELETE
